settings:
    files:
        outputs:
            status: false
            path: ''
            name: .r.outputs.log
        logs:
            status: false
            path: ''
            name: .r.logs.log
        errors:
            status: false
            path: ''
            name: .r.errors.log
    legacy:
        force: false
        interval: 0s
schema:
    -   name: linkshortener
        path: .
        commands:
            install:
                status: true
                method: go build -o build/linkshortener
            run:
                status: true
                method: build/linkshortener
        watcher:
            extensions:
                - go
            paths:
                - /
            ignore:
                paths:
                    - .git
                    - .realize
                    - .idea
                    - docker
