version: '3.7'

services:
    postgres:
        image: postgres:12.1
        environment:
            POSTGRES_PASSWORD: "Ceihohch8ait5"
        ports:
            - 5432:5432
#        volumes:
#            - ./docker/postgress/data:/var/lib/postgresql/data
        restart: unless-stopped
